fasta_dir: /stgTematico/projects/tematicoNelore/workspace/Taina/geracao/mags_papers/drep/dereplicated_genomes/
out_dir: /stgTematico/projects/tematicoNelore/workspace/Taina/geracao/holomira_assoc_mags/RME
sample_tab: /stgTematico/projects/tematicoNelore/workspace/Taina/geracao/holomira_assoc_mags/sample_tab_rme
upstream: 15
downstream: 20
ref_mir: /stgTematico/projects/tematicoNelore/workspace/Taina/geracao/holomira_assoc_mags/miRNA_RME_expressed.fa
seed: 2,8
energy: -18
pvalue: 0.01
id: /stgTematico/projects/tematicoNelore/workspace/Taina/geracao/holomira_assoc_mags/id_bos_RME
environment: ["decrease_RME", "increase_RME"]
