fasta_dir: Example_data/Genomes_files/
out_dir: Results
sample_tab: Example_data/samples_id
ref_mir: Example_data/miRNAs.fa
id: Example_data/metadata_samples
environment: ["Rumen", "Feces"]

##Parameters
upstream: 15
downstream: 20
seed: NA
energy: -20
pvalue: 0.01
DGopen_cutoff: -15